(cl:defpackage iri_bow_object_detector-msg
  (:use )
  (:export
   "<WRINKLEDMAP>"
   "WRINKLEDMAP"
   "<GETGRASPINGPOINTFEEDBACK>"
   "GETGRASPINGPOINTFEEDBACK"
   "<GETGRASPINGPOINTACTION>"
   "GETGRASPINGPOINTACTION"
   "<OBJECTBOX>"
   "OBJECTBOX"
   "<GETGRASPINGPOINTGOAL>"
   "GETGRASPINGPOINTGOAL"
   "<GETGRASPINGPOINTRESULT>"
   "GETGRASPINGPOINTRESULT"
   "<GETGRASPINGPOINTACTIONRESULT>"
   "GETGRASPINGPOINTACTIONRESULT"
   "<GETGRASPINGPOINTACTIONGOAL>"
   "GETGRASPINGPOINTACTIONGOAL"
   "<GETGRASPINGPOINTACTIONFEEDBACK>"
   "GETGRASPINGPOINTACTIONFEEDBACK"
  ))

