(cl:defpackage door_detector_pal-msg
  (:use )
  (:export
   "<DOORDETECTORFEEDBACK>"
   "DOORDETECTORFEEDBACK"
   "<DOORDETECTORGOAL>"
   "DOORDETECTORGOAL"
   "<DOORDETECTORACTIONGOAL>"
   "DOORDETECTORACTIONGOAL"
   "<DOORDETECTORACTIONRESULT>"
   "DOORDETECTORACTIONRESULT"
   "<DOORDETECTORACTIONFEEDBACK>"
   "DOORDETECTORACTIONFEEDBACK"
   "<DOORDETECTORACTION>"
   "DOORDETECTORACTION"
   "<DOORDETECTORRESULT>"
   "DOORDETECTORRESULT"
  ))

