/* Auto-generated by genmsg_cpp for file /home/sampfeiffer/branches_svn/migration/ROBOCUP_STACKS_INTEGRATION/stacks/robocup_stacks/iri/estirabot_msgs/msg/GraspVerification.msg */
#ifndef ESTIRABOT_MSGS_MESSAGE_GRASPVERIFICATION_H
#define ESTIRABOT_MSGS_MESSAGE_GRASPVERIFICATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "object_manipulation_msgs/GraspResult.h"
#include "sensor_msgs/PointCloud2.h"

namespace estirabot_msgs
{
template <class ContainerAllocator>
struct GraspVerification_ {
  typedef GraspVerification_<ContainerAllocator> Type;

  GraspVerification_()
  : grasp_results()
  , grasp_images()
  {
  }

  GraspVerification_(const ContainerAllocator& _alloc)
  : grasp_results(_alloc)
  , grasp_images(_alloc)
  {
  }

  typedef std::vector< ::object_manipulation_msgs::GraspResult_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_manipulation_msgs::GraspResult_<ContainerAllocator> >::other >  _grasp_results_type;
  std::vector< ::object_manipulation_msgs::GraspResult_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_manipulation_msgs::GraspResult_<ContainerAllocator> >::other >  grasp_results;

  typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  _grasp_images_type;
  std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  grasp_images;

  enum { AFTER_LIFT = 0 };
  enum { AFTER_SHAKING = 1 };

  typedef boost::shared_ptr< ::estirabot_msgs::GraspVerification_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::estirabot_msgs::GraspVerification_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GraspVerification
typedef  ::estirabot_msgs::GraspVerification_<std::allocator<void> > GraspVerification;

typedef boost::shared_ptr< ::estirabot_msgs::GraspVerification> GraspVerificationPtr;
typedef boost::shared_ptr< ::estirabot_msgs::GraspVerification const> GraspVerificationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::estirabot_msgs::GraspVerification_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::estirabot_msgs::GraspVerification_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace estirabot_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::estirabot_msgs::GraspVerification_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::estirabot_msgs::GraspVerification_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::estirabot_msgs::GraspVerification_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e3d204a43e7cce62c1853351b215f13e";
  }

  static const char* value(const  ::estirabot_msgs::GraspVerification_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe3d204a43e7cce62ULL;
  static const uint64_t static_value2 = 0xc1853351b215f13eULL;
};

template<class ContainerAllocator>
struct DataType< ::estirabot_msgs::GraspVerification_<ContainerAllocator> > {
  static const char* value() 
  {
    return "estirabot_msgs/GraspVerification";
  }

  static const char* value(const  ::estirabot_msgs::GraspVerification_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::estirabot_msgs::GraspVerification_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Message containing results from a sequence of verification actions on a grasAFTER_SHAKING = 1p\n\
\n\
# Currently positions in the vector correspond to the following actions\n\
# 0 -> Result after basic lift movement\n\
# 1 -> Result after shaking the cloth when lifted\n\
\n\
int32 AFTER_LIFT = 0\n\
int32 AFTER_SHAKING = 1\n\
\n\
object_manipulation_msgs/GraspResult[] grasp_results\n\
sensor_msgs/PointCloud2[] grasp_images\n\
\n\
================================================================================\n\
MSG: object_manipulation_msgs/GraspResult\n\
int32 SUCCESS = 1\n\
int32 GRASP_OUT_OF_REACH = 2\n\
int32 GRASP_IN_COLLISION = 3\n\
int32 GRASP_UNFEASIBLE = 4\n\
int32 PREGRASP_OUT_OF_REACH = 5\n\
int32 PREGRASP_IN_COLLISION = 6\n\
int32 PREGRASP_UNFEASIBLE = 7\n\
int32 LIFT_OUT_OF_REACH = 8\n\
int32 LIFT_IN_COLLISION = 9\n\
int32 LIFT_UNFEASIBLE = 10\n\
int32 MOVE_ARM_FAILED = 11\n\
int32 GRASP_FAILED = 12\n\
int32 LIFT_FAILED = 13\n\
int32 RETREAT_FAILED = 14\n\
int32 result_code\n\
\n\
# whether the state of the world was disturbed by this attempt. generally, this flag\n\
# shows if another task can be attempted, or a new sensed world model is recommeded\n\
# before proceeding\n\
bool continuation_possible\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
";
  }

  static const char* value(const  ::estirabot_msgs::GraspVerification_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::estirabot_msgs::GraspVerification_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.grasp_results);
    stream.next(m.grasp_images);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GraspVerification_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::estirabot_msgs::GraspVerification_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::estirabot_msgs::GraspVerification_<ContainerAllocator> & v) 
  {
    s << indent << "grasp_results[]" << std::endl;
    for (size_t i = 0; i < v.grasp_results.size(); ++i)
    {
      s << indent << "  grasp_results[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_manipulation_msgs::GraspResult_<ContainerAllocator> >::stream(s, indent + "    ", v.grasp_results[i]);
    }
    s << indent << "grasp_images[]" << std::endl;
    for (size_t i = 0; i < v.grasp_images.size(); ++i)
    {
      s << indent << "  grasp_images[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.grasp_images[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ESTIRABOT_MSGS_MESSAGE_GRASPVERIFICATION_H

