(cl:defpackage estirabot_msgs-msg
  (:use )
  (:export
   "<BELIEF_SUMMARY>"
   "BELIEF_SUMMARY"
   "<TRAVERSEDELLIPSES>"
   "TRAVERSEDELLIPSES"
   "<BELIEF>"
   "BELIEF"
   "<DIRTYAREA>"
   "DIRTYAREA"
   "<ARRAYINDEXES>"
   "ARRAYINDEXES"
   "<GRASPVERIFICATION>"
   "GRASPVERIFICATION"
   "<POINTSDISTANCEMSG>"
   "POINTSDISTANCEMSG"
   "<ELLIPSE>"
   "ELLIPSE"
   "<GRASPPOINTPARAMETERS>"
   "GRASPPOINTPARAMETERS"
   "<POMDPGRASPCONFIG>"
   "POMDPGRASPCONFIG"
  ))

