/* Auto-generated by genmsg_cpp for file /home/sampfeiffer/branches_svn/migration/ROBOCUP_STACKS_INTEGRATION/stacks/robocup_stacks/iri/iri_perception_msgs/msg/peopleTracking.msg */
#ifndef IRI_PERCEPTION_MSGS_MESSAGE_PEOPLETRACKING_H
#define IRI_PERCEPTION_MSGS_MESSAGE_PEOPLETRACKING_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace iri_perception_msgs
{
template <class ContainerAllocator>
struct peopleTracking_ {
  typedef peopleTracking_<ContainerAllocator> Type;

  peopleTracking_()
  : targetId(0)
  , targetStatus(0)
  , x(0.0)
  , y(0.0)
  , vx(0.0)
  , vy(0.0)
  , covariances()
  {
    covariances.assign(0.0);
  }

  peopleTracking_(const ContainerAllocator& _alloc)
  : targetId(0)
  , targetStatus(0)
  , x(0.0)
  , y(0.0)
  , vx(0.0)
  , vy(0.0)
  , covariances()
  {
    covariances.assign(0.0);
  }

  typedef int32_t _targetId_type;
  int32_t targetId;

  typedef int32_t _targetStatus_type;
  int32_t targetStatus;

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _vx_type;
  double vx;

  typedef double _vy_type;
  double vy;

  typedef boost::array<double, 16>  _covariances_type;
  boost::array<double, 16>  covariances;


  typedef boost::shared_ptr< ::iri_perception_msgs::peopleTracking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_perception_msgs::peopleTracking_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct peopleTracking
typedef  ::iri_perception_msgs::peopleTracking_<std::allocator<void> > peopleTracking;

typedef boost::shared_ptr< ::iri_perception_msgs::peopleTracking> peopleTrackingPtr;
typedef boost::shared_ptr< ::iri_perception_msgs::peopleTracking const> peopleTrackingConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::iri_perception_msgs::peopleTracking_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::iri_perception_msgs::peopleTracking_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace iri_perception_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::iri_perception_msgs::peopleTracking_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::iri_perception_msgs::peopleTracking_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::iri_perception_msgs::peopleTracking_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5085acdc7b3d2430f148e7a5cb50043c";
  }

  static const char* value(const  ::iri_perception_msgs::peopleTracking_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5085acdc7b3d2430ULL;
  static const uint64_t static_value2 = 0xf148e7a5cb50043cULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_perception_msgs::peopleTracking_<ContainerAllocator> > {
  static const char* value() 
  {
    return "iri_perception_msgs/peopleTracking";
  }

  static const char* value(const  ::iri_perception_msgs::peopleTracking_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::iri_perception_msgs::peopleTracking_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#target id\n\
int32 targetId\n\
\n\
#target status is a bitwise OR of the following values\n\
#      TO_BE_REMOVED = 0x01,\n\
#      OCCLUDDED = 0x02,\n\
#      CANDIDATE = 0x04,\n\
#      LEGGED_TARGET = 0x08,\n\
#      VISUALLY_CONFIRMED = 0x10,\n\
#      FRIEND_IN_SIGHT = 0x20,\n\
#      BACK_LEARNT = 0x40,\n\
#      FACE_LEARNT = 0x80\n\
int32 targetStatus\n\
\n\
#target 2D position\n\
float64 x\n\
float64 y\n\
\n\
#target 2D linear velocity\n\
float64 vx\n\
float64 vy\n\
\n\
#(x,y,vx,vy) covariance matrix\n\
float64[16] covariances\n\
";
  }

  static const char* value(const  ::iri_perception_msgs::peopleTracking_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::iri_perception_msgs::peopleTracking_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::iri_perception_msgs::peopleTracking_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.targetId);
    stream.next(m.targetStatus);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.vx);
    stream.next(m.vy);
    stream.next(m.covariances);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct peopleTracking_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_perception_msgs::peopleTracking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::iri_perception_msgs::peopleTracking_<ContainerAllocator> & v) 
  {
    s << indent << "targetId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.targetId);
    s << indent << "targetStatus: ";
    Printer<int32_t>::stream(s, indent + "  ", v.targetStatus);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "covariances[]" << std::endl;
    for (size_t i = 0; i < v.covariances.size(); ++i)
    {
      s << indent << "  covariances[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.covariances[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // IRI_PERCEPTION_MSGS_MESSAGE_PEOPLETRACKING_H

