(cl:in-package pr_msgs-srv)
(cl:export '(JOINT_STATE-VAL
          JOINT_STATE
          CURRENT_SELF_COLLISION-VAL
          CURRENT_SELF_COLLISION
          CURRENT_ENV_COLLISION-VAL
          CURRENT_ENV_COLLISION
          FUTURE_SELF_COLLISION-VAL
          FUTURE_SELF_COLLISION
          FUTURE_ENV_COLLISION-VAL
          FUTURE_ENV_COLLISION
          CURRENT_JOINT_LIMITS_EXCEEDED-VAL
          CURRENT_JOINT_LIMITS_EXCEEDED
          FUTURE_JOINT_LIMITS_EXCEEDED-VAL
          FUTURE_JOINT_LIMITS_EXCEEDED
))