(cl:defpackage coord_translator-srv
  (:use )
  (:export
   "OBJECTTRANSLATORDATABASE"
   "<OBJECTTRANSLATORDATABASE-REQUEST>"
   "OBJECTTRANSLATORDATABASE-REQUEST"
   "<OBJECTTRANSLATORDATABASE-RESPONSE>"
   "OBJECTTRANSLATORDATABASE-RESPONSE"
   "LOCATIONTRANSLATOR"
   "<LOCATIONTRANSLATOR-REQUEST>"
   "LOCATIONTRANSLATOR-REQUEST"
   "<LOCATIONTRANSLATOR-RESPONSE>"
   "LOCATIONTRANSLATOR-RESPONSE"
   "OBJECTTRANSLATOR"
   "<OBJECTTRANSLATOR-REQUEST>"
   "OBJECTTRANSLATOR-REQUEST"
   "<OBJECTTRANSLATOR-RESPONSE>"
   "OBJECTTRANSLATOR-RESPONSE"
  ))

