"""autogenerated by genpy from pr_msgs/RailsState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RailsState(genpy.Message):
  _md5sum = "ce17ce4ba137fd794491e233128e6635"
  _type = "pr_msgs/RailsState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string goal_station_name
float64 goal_station_distance
string prev_station_name
float64 prev_station_distance
string closest_station_name
float64 closest_station_distance

"""
  __slots__ = ['goal_station_name','goal_station_distance','prev_station_name','prev_station_distance','closest_station_name','closest_station_distance']
  _slot_types = ['string','float64','string','float64','string','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       goal_station_name,goal_station_distance,prev_station_name,prev_station_distance,closest_station_name,closest_station_distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RailsState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.goal_station_name is None:
        self.goal_station_name = ''
      if self.goal_station_distance is None:
        self.goal_station_distance = 0.
      if self.prev_station_name is None:
        self.prev_station_name = ''
      if self.prev_station_distance is None:
        self.prev_station_distance = 0.
      if self.closest_station_name is None:
        self.closest_station_name = ''
      if self.closest_station_distance is None:
        self.closest_station_distance = 0.
    else:
      self.goal_station_name = ''
      self.goal_station_distance = 0.
      self.prev_station_name = ''
      self.prev_station_distance = 0.
      self.closest_station_name = ''
      self.closest_station_distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.goal_station_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_d.pack(self.goal_station_distance))
      _x = self.prev_station_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_d.pack(self.prev_station_distance))
      _x = self.closest_station_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_d.pack(self.closest_station_distance))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_station_name = str[start:end].decode('utf-8')
      else:
        self.goal_station_name = str[start:end]
      start = end
      end += 8
      (self.goal_station_distance,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.prev_station_name = str[start:end].decode('utf-8')
      else:
        self.prev_station_name = str[start:end]
      start = end
      end += 8
      (self.prev_station_distance,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.closest_station_name = str[start:end].decode('utf-8')
      else:
        self.closest_station_name = str[start:end]
      start = end
      end += 8
      (self.closest_station_distance,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.goal_station_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_d.pack(self.goal_station_distance))
      _x = self.prev_station_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_d.pack(self.prev_station_distance))
      _x = self.closest_station_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_d.pack(self.closest_station_distance))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_station_name = str[start:end].decode('utf-8')
      else:
        self.goal_station_name = str[start:end]
      start = end
      end += 8
      (self.goal_station_distance,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.prev_station_name = str[start:end].decode('utf-8')
      else:
        self.prev_station_name = str[start:end]
      start = end
      end += 8
      (self.prev_station_distance,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.closest_station_name = str[start:end].decode('utf-8')
      else:
        self.closest_station_name = str[start:end]
      start = end
      end += 8
      (self.closest_station_distance,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_d = struct.Struct("<d")
