(cl:defpackage iri_bow_object_detector-srv
  (:use )
  (:export
   "GEOVWDETECTION"
   "<GEOVWDETECTION-REQUEST>"
   "GEOVWDETECTION-REQUEST"
   "<GEOVWDETECTION-RESPONSE>"
   "GEOVWDETECTION-RESPONSE"
   "REFINEGRASPPOINT"
   "<REFINEGRASPPOINT-REQUEST>"
   "REFINEGRASPPOINT-REQUEST"
   "<REFINEGRASPPOINT-RESPONSE>"
   "REFINEGRASPPOINT-RESPONSE"
  ))

