(cl:defpackage next_location_provider-srv
  (:use )
  (:export
   "NEXTPROBABLELOCATION"
   "<NEXTPROBABLELOCATION-REQUEST>"
   "NEXTPROBABLELOCATION-REQUEST"
   "<NEXTPROBABLELOCATION-RESPONSE>"
   "NEXTPROBABLELOCATION-RESPONSE"
  ))

