/* Auto-generated by genmsg_cpp for file /home/sampfeiffer/branches_svn/migration/ROBOCUP_STACKS_INTEGRATION/stacks/robocup_stacks/iri/iri_wam_common_msgs/msg/LWPRTrajectoryReturningForceEstimationFeedback.msg */
#ifndef IRI_WAM_COMMON_MSGS_MESSAGE_LWPRTRAJECTORYRETURNINGFORCEESTIMATIONFEEDBACK_H
#define IRI_WAM_COMMON_MSGS_MESSAGE_LWPRTRAJECTORYRETURNINGFORCEESTIMATIONFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace iri_wam_common_msgs
{
template <class ContainerAllocator>
struct LWPRTrajectoryReturningForceEstimationFeedback_ {
  typedef LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> Type;

  LWPRTrajectoryReturningForceEstimationFeedback_()
  {
  }

  LWPRTrajectoryReturningForceEstimationFeedback_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LWPRTrajectoryReturningForceEstimationFeedback
typedef  ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<std::allocator<void> > LWPRTrajectoryReturningForceEstimationFeedback;

typedef boost::shared_ptr< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback> LWPRTrajectoryReturningForceEstimationFeedbackPtr;
typedef boost::shared_ptr< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback const> LWPRTrajectoryReturningForceEstimationFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace iri_wam_common_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "iri_wam_common_msgs/LWPRTrajectoryReturningForceEstimationFeedback";
  }

  static const char* value(const  ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# feedback\n\
\n\
\n\
";
  }

  static const char* value(const  ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LWPRTrajectoryReturningForceEstimationFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::iri_wam_common_msgs::LWPRTrajectoryReturningForceEstimationFeedback_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // IRI_WAM_COMMON_MSGS_MESSAGE_LWPRTRAJECTORYRETURNINGFORCEESTIMATIONFEEDBACK_H

