/* Auto-generated by genmsg_cpp for file /home/sampfeiffer/branches_svn/migration/ROBOCUP_STACKS_INTEGRATION/stacks/robocup_stacks/iri/normal_descriptor_node/msg/ndesc.msg */
#ifndef NORMAL_DESCRIPTOR_NODE_MESSAGE_NDESC_H
#define NORMAL_DESCRIPTOR_NODE_MESSAGE_NDESC_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/Vector3.h"

namespace normal_descriptor_node
{
template <class ContainerAllocator>
struct ndesc_ {
  typedef ndesc_<ContainerAllocator> Type;

  ndesc_()
  : descriptor()
  , point3d()
  , u(0)
  , v(0)
  , ori(0.0)
  {
  }

  ndesc_(const ContainerAllocator& _alloc)
  : descriptor(_alloc)
  , point3d(_alloc)
  , u(0)
  , v(0)
  , ori(0.0)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _descriptor_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  descriptor;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _point3d_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  point3d;

  typedef int32_t _u_type;
  int32_t u;

  typedef int32_t _v_type;
  int32_t v;

  typedef float _ori_type;
  float ori;


  typedef boost::shared_ptr< ::normal_descriptor_node::ndesc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::normal_descriptor_node::ndesc_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ndesc
typedef  ::normal_descriptor_node::ndesc_<std::allocator<void> > ndesc;

typedef boost::shared_ptr< ::normal_descriptor_node::ndesc> ndescPtr;
typedef boost::shared_ptr< ::normal_descriptor_node::ndesc const> ndescConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::normal_descriptor_node::ndesc_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::normal_descriptor_node::ndesc_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace normal_descriptor_node

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::normal_descriptor_node::ndesc_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::normal_descriptor_node::ndesc_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::normal_descriptor_node::ndesc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6efcdd88f5aa9024bcc7df7fd26a0f88";
  }

  static const char* value(const  ::normal_descriptor_node::ndesc_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6efcdd88f5aa9024ULL;
  static const uint64_t static_value2 = 0xbcc7df7fd26a0f88ULL;
};

template<class ContainerAllocator>
struct DataType< ::normal_descriptor_node::ndesc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "normal_descriptor_node/ndesc";
  }

  static const char* value(const  ::normal_descriptor_node::ndesc_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::normal_descriptor_node::ndesc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] descriptor\n\
geometry_msgs/Vector3 point3d\n\
int32 u\n\
int32 v\n\
float32 ori\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::normal_descriptor_node::ndesc_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::normal_descriptor_node::ndesc_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.descriptor);
    stream.next(m.point3d);
    stream.next(m.u);
    stream.next(m.v);
    stream.next(m.ori);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ndesc_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::normal_descriptor_node::ndesc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::normal_descriptor_node::ndesc_<ContainerAllocator> & v) 
  {
    s << indent << "descriptor[]" << std::endl;
    for (size_t i = 0; i < v.descriptor.size(); ++i)
    {
      s << indent << "  descriptor[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.descriptor[i]);
    }
    s << indent << "point3d: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.point3d);
    s << indent << "u: ";
    Printer<int32_t>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<int32_t>::stream(s, indent + "  ", v.v);
    s << indent << "ori: ";
    Printer<float>::stream(s, indent + "  ", v.ori);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NORMAL_DESCRIPTOR_NODE_MESSAGE_NDESC_H

