(cl:defpackage iri_publish_params-srv
  (:use )
  (:export
   "CLASSIFIER_UPDATE_SERVICE"
   "<CLASSIFIER_UPDATE_SERVICE-REQUEST>"
   "CLASSIFIER_UPDATE_SERVICE-REQUEST"
   "<CLASSIFIER_UPDATE_SERVICE-RESPONSE>"
   "CLASSIFIER_UPDATE_SERVICE-RESPONSE"
  ))

