(cl:defpackage iri_door_detector-msg
  (:use )
  (:export
   "<FINDADOORACTIONFEEDBACK>"
   "FINDADOORACTIONFEEDBACK"
   "<FINDADOORACTION>"
   "FINDADOORACTION"
   "<FINDADOORACTIONRESULT>"
   "FINDADOORACTIONRESULT"
   "<FINDADOORFEEDBACK>"
   "FINDADOORFEEDBACK"
   "<FINDADOORGOAL>"
   "FINDADOORGOAL"
   "<FINDADOORRESULT>"
   "FINDADOORRESULT"
   "<FINDADOORACTIONGOAL>"
   "FINDADOORACTIONGOAL"
  ))

