(cl:in-package pr_msgs-msg)
(cl:export '(GOAL_STATION_NAME-VAL
          GOAL_STATION_NAME
          GOAL_STATION_DISTANCE-VAL
          GOAL_STATION_DISTANCE
          PREV_STATION_NAME-VAL
          PREV_STATION_NAME
          PREV_STATION_DISTANCE-VAL
          PREV_STATION_DISTANCE
          CLOSEST_STATION_NAME-VAL
          CLOSEST_STATION_NAME
          CLOSEST_STATION_DISTANCE-VAL
          CLOSEST_STATION_DISTANCE
))