; Auto-generated. Do not edit!


(cl:in-package pr_msgs-msg)


;//! \htmlinclude SignalGoal.msg.html

(cl:defclass <SignalGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SignalGoal (<SignalGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SignalGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SignalGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr_msgs-msg:<SignalGoal> is deprecated: use pr_msgs-msg:SignalGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SignalGoal>) ostream)
  "Serializes a message object of type '<SignalGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SignalGoal>) istream)
  "Deserializes a message object of type '<SignalGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SignalGoal>)))
  "Returns string type for a message object of type '<SignalGoal>"
  "pr_msgs/SignalGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SignalGoal)))
  "Returns string type for a message object of type 'SignalGoal"
  "pr_msgs/SignalGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SignalGoal>)))
  "Returns md5sum for a message object of type '<SignalGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SignalGoal)))
  "Returns md5sum for a message object of type 'SignalGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SignalGoal>)))
  "Returns full string definition for message of type '<SignalGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SignalGoal)))
  "Returns full string definition for message of type 'SignalGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SignalGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SignalGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SignalGoal
))
