(cl:defpackage iri_motion_detector-msg
  (:use )
  (:export
   "<MOTIONDETECTORACTIONRESULT>"
   "MOTIONDETECTORACTIONRESULT"
   "<MOTIONDETECTORACTIONFEEDBACK>"
   "MOTIONDETECTORACTIONFEEDBACK"
   "<MOTIONDETECTORACTIONACTIONRESULT>"
   "MOTIONDETECTORACTIONACTIONRESULT"
   "<MOTIONDETECTORACTIONACTIONGOAL>"
   "MOTIONDETECTORACTIONACTIONGOAL"
   "<MOTIONDETECTORACTIONACTIONFEEDBACK>"
   "MOTIONDETECTORACTIONACTIONFEEDBACK"
   "<MOTIONDETECTORACTIONGOAL>"
   "MOTIONDETECTORACTIONGOAL"
   "<MOTIONDETECTORACTIONACTION>"
   "MOTIONDETECTORACTIONACTION"
  ))

