(cl:defpackage restaurant-srv
  (:use )
  (:export
   "LOOKUPTRANSFORM"
   "<LOOKUPTRANSFORM-REQUEST>"
   "LOOKUPTRANSFORM-REQUEST"
   "<LOOKUPTRANSFORM-RESPONSE>"
   "LOOKUPTRANSFORM-RESPONSE"
  ))

