(cl:defpackage upperbody_mock-msg
  (:use )
  (:export
   "<UPPERBODYGOAL>"
   "UPPERBODYGOAL"
   "<UPPERBODYRESULT>"
   "UPPERBODYRESULT"
   "<UPPERBODYACTIONRESULT>"
   "UPPERBODYACTIONRESULT"
   "<UPPERBODYACTIONFEEDBACK>"
   "UPPERBODYACTIONFEEDBACK"
   "<UPPERBODYACTIONGOAL>"
   "UPPERBODYACTIONGOAL"
   "<UPPERBODYFEEDBACK>"
   "UPPERBODYFEEDBACK"
   "<UPPERBODYACTION>"
   "UPPERBODYACTION"
  ))

