(cl:defpackage gpsrSoar-msg
  (:use )
  (:export
   "<GPSRACTIONACTIONFEEDBACK>"
   "GPSRACTIONACTIONFEEDBACK"
   "<GPSRACTIONACTIONRESULT>"
   "GPSRACTIONACTIONRESULT"
   "<GPSRACTIONRESULT>"
   "GPSRACTIONRESULT"
   "<ORDER>"
   "ORDER"
   "<GPSRACTIONACTION>"
   "GPSRACTIONACTION"
   "<GPSRACTIONACTIONGOAL>"
   "GPSRACTIONACTIONGOAL"
   "<GPSRACTIONGOAL>"
   "GPSRACTIONGOAL"
   "<GPSRACTIONFEEDBACK>"
   "GPSRACTIONFEEDBACK"
  ))

