/* Auto-generated by genmsg_cpp for file /home/sampfeiffer/branches_svn/migration/ROBOCUP_STACKS_INTEGRATION/stacks/robocup_stacks/moped/pr_msgs/srv/WamRequestSeaCtrlKd.srv */
#ifndef PR_MSGS_SERVICE_WAMREQUESTSEACTRLKD_H
#define PR_MSGS_SERVICE_WAMREQUESTSEACTRLKD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace pr_msgs
{
template <class ContainerAllocator>
struct WamRequestSeaCtrlKdRequest_ {
  typedef WamRequestSeaCtrlKdRequest_<ContainerAllocator> Type;

  WamRequestSeaCtrlKdRequest_()
  {
  }

  WamRequestSeaCtrlKdRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct WamRequestSeaCtrlKdRequest
typedef  ::pr_msgs::WamRequestSeaCtrlKdRequest_<std::allocator<void> > WamRequestSeaCtrlKdRequest;

typedef boost::shared_ptr< ::pr_msgs::WamRequestSeaCtrlKdRequest> WamRequestSeaCtrlKdRequestPtr;
typedef boost::shared_ptr< ::pr_msgs::WamRequestSeaCtrlKdRequest const> WamRequestSeaCtrlKdRequestConstPtr;


template <class ContainerAllocator>
struct WamRequestSeaCtrlKdResponse_ {
  typedef WamRequestSeaCtrlKdResponse_<ContainerAllocator> Type;

  WamRequestSeaCtrlKdResponse_()
  {
  }

  WamRequestSeaCtrlKdResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct WamRequestSeaCtrlKdResponse
typedef  ::pr_msgs::WamRequestSeaCtrlKdResponse_<std::allocator<void> > WamRequestSeaCtrlKdResponse;

typedef boost::shared_ptr< ::pr_msgs::WamRequestSeaCtrlKdResponse> WamRequestSeaCtrlKdResponsePtr;
typedef boost::shared_ptr< ::pr_msgs::WamRequestSeaCtrlKdResponse const> WamRequestSeaCtrlKdResponseConstPtr;

struct WamRequestSeaCtrlKd
{

typedef WamRequestSeaCtrlKdRequest Request;
typedef WamRequestSeaCtrlKdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct WamRequestSeaCtrlKd
} // namespace pr_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr_msgs/WamRequestSeaCtrlKdRequest";
  }

  static const char* value(const  ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr_msgs/WamRequestSeaCtrlKdResponse";
  }

  static const char* value(const  ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WamRequestSeaCtrlKdRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WamRequestSeaCtrlKdResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<pr_msgs::WamRequestSeaCtrlKd> {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const pr_msgs::WamRequestSeaCtrlKd&) { return value(); } 
};

template<>
struct DataType<pr_msgs::WamRequestSeaCtrlKd> {
  static const char* value() 
  {
    return "pr_msgs/WamRequestSeaCtrlKd";
  }

  static const char* value(const pr_msgs::WamRequestSeaCtrlKd&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr_msgs/WamRequestSeaCtrlKd";
  }

  static const char* value(const pr_msgs::WamRequestSeaCtrlKdRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pr_msgs/WamRequestSeaCtrlKd";
  }

  static const char* value(const pr_msgs::WamRequestSeaCtrlKdResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // PR_MSGS_SERVICE_WAMREQUESTSEACTRLKD_H

