/* Auto-generated by genmsg_cpp for file /home/sampfeiffer/branches_svn/migration/ROBOCUP_STACKS_INTEGRATION/stacks/robocup_stacks/door_detector_pal/msg/DoorDetectorFeedback.msg */
#ifndef DOOR_DETECTOR_PAL_MESSAGE_DOORDETECTORFEEDBACK_H
#define DOOR_DETECTOR_PAL_MESSAGE_DOORDETECTORFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace door_detector_pal
{
template <class ContainerAllocator>
struct DoorDetectorFeedback_ {
  typedef DoorDetectorFeedback_<ContainerAllocator> Type;

  DoorDetectorFeedback_()
  : comment()
  {
  }

  DoorDetectorFeedback_(const ContainerAllocator& _alloc)
  : comment(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _comment_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  comment;


  typedef boost::shared_ptr< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DoorDetectorFeedback
typedef  ::door_detector_pal::DoorDetectorFeedback_<std::allocator<void> > DoorDetectorFeedback;

typedef boost::shared_ptr< ::door_detector_pal::DoorDetectorFeedback> DoorDetectorFeedbackPtr;
typedef boost::shared_ptr< ::door_detector_pal::DoorDetectorFeedback const> DoorDetectorFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace door_detector_pal

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "83609817d68993e8cc8571226bf4197d";
  }

  static const char* value(const  ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x83609817d68993e8ULL;
  static const uint64_t static_value2 = 0xcc8571226bf4197dULL;
};

template<class ContainerAllocator>
struct DataType< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "door_detector_pal/DoorDetectorFeedback";
  }

  static const char* value(const  ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Feedback\n\
string comment\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.comment);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DoorDetectorFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::door_detector_pal::DoorDetectorFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "comment: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.comment);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DOOR_DETECTOR_PAL_MESSAGE_DOORDETECTORFEEDBACK_H

