(cl:defpackage iri_sift-srv
  (:use )
  (:export
   "DESCRIPTORSFROMIMAGE"
   "<DESCRIPTORSFROMIMAGE-REQUEST>"
   "DESCRIPTORSFROMIMAGE-REQUEST"
   "<DESCRIPTORSFROMIMAGE-RESPONSE>"
   "DESCRIPTORSFROMIMAGE-RESPONSE"
   "GEOVWSETSRV"
   "<GEOVWSETSRV-REQUEST>"
   "GEOVWSETSRV-REQUEST"
   "<GEOVWSETSRV-RESPONSE>"
   "GEOVWSETSRV-RESPONSE"
  ))

