/* Auto-generated by genmsg_cpp for file /home/sampfeiffer/branches_svn/migration/ROBOCUP_STACKS_INTEGRATION/stacks/robocup_stacks/state_machines/gpsr/msg/order_list.msg */
#ifndef GPSR_MESSAGE_ORDER_LIST_H
#define GPSR_MESSAGE_ORDER_LIST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "gpsr/order.h"

namespace gpsr
{
template <class ContainerAllocator>
struct order_list_ {
  typedef order_list_<ContainerAllocator> Type;

  order_list_()
  : actionSet()
  {
  }

  order_list_(const ContainerAllocator& _alloc)
  : actionSet(_alloc)
  {
  }

  typedef std::vector< ::gpsr::order_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gpsr::order_<ContainerAllocator> >::other >  _actionSet_type;
  std::vector< ::gpsr::order_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gpsr::order_<ContainerAllocator> >::other >  actionSet;


  typedef boost::shared_ptr< ::gpsr::order_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpsr::order_list_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct order_list
typedef  ::gpsr::order_list_<std::allocator<void> > order_list;

typedef boost::shared_ptr< ::gpsr::order_list> order_listPtr;
typedef boost::shared_ptr< ::gpsr::order_list const> order_listConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::gpsr::order_list_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::gpsr::order_list_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace gpsr

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::gpsr::order_list_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::gpsr::order_list_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::gpsr::order_list_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4056d793c91331c5f484bd54042199ea";
  }

  static const char* value(const  ::gpsr::order_list_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4056d793c91331c5ULL;
  static const uint64_t static_value2 = 0xf484bd54042199eaULL;
};

template<class ContainerAllocator>
struct DataType< ::gpsr::order_list_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gpsr/order_list";
  }

  static const char* value(const  ::gpsr::order_list_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gpsr::order_list_<ContainerAllocator> > {
  static const char* value() 
  {
    return "order[] actionSet\n\
\n\
================================================================================\n\
MSG: gpsr/order\n\
string action\n\
string person\n\
string location\n\
string item\n\
string[] other\n\
\n\
";
  }

  static const char* value(const  ::gpsr::order_list_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gpsr::order_list_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.actionSet);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct order_list_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpsr::order_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::gpsr::order_list_<ContainerAllocator> & v) 
  {
    s << indent << "actionSet[]" << std::endl;
    for (size_t i = 0; i < v.actionSet.size(); ++i)
    {
      s << indent << "  actionSet[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gpsr::order_<ContainerAllocator> >::stream(s, indent + "    ", v.actionSet[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // GPSR_MESSAGE_ORDER_LIST_H

