(cl:defpackage iri_moped_actionserver-msg
  (:use )
  (:export
   "<MOPEDRESULT>"
   "MOPEDRESULT"
   "<MOPEDACTION>"
   "MOPEDACTION"
   "<MOPEDFEEDBACK>"
   "MOPEDFEEDBACK"
   "<MOPEDACTIONGOAL>"
   "MOPEDACTIONGOAL"
   "<MOPEDACTIONFEEDBACK>"
   "MOPEDACTIONFEEDBACK"
   "<MOPEDACTIONRESULT>"
   "MOPEDACTIONRESULT"
   "<MOPEDGOAL>"
   "MOPEDGOAL"
  ))

