/* Auto-generated by genmsg_cpp for file /home/sampfeiffer/branches_svn/migration/ROBOCUP_STACKS_INTEGRATION/stacks/robocup_stacks/iri/iri_sift/srv/GeoVwSetSrv.srv */
#ifndef IRI_SIFT_SERVICE_GEOVWSETSRV_H
#define IRI_SIFT_SERVICE_GEOVWSETSRV_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "sensor_msgs/Image.h"


#include "iri_perception_msgs/GeoVwSet.h"

namespace iri_sift
{
template <class ContainerAllocator>
struct GeoVwSetSrvRequest_ {
  typedef GeoVwSetSrvRequest_<ContainerAllocator> Type;

  GeoVwSetSrvRequest_()
  : image()
  {
  }

  GeoVwSetSrvRequest_(const ContainerAllocator& _alloc)
  : image(_alloc)
  {
  }

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
   ::sensor_msgs::Image_<ContainerAllocator>  image;


  typedef boost::shared_ptr< ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GeoVwSetSrvRequest
typedef  ::iri_sift::GeoVwSetSrvRequest_<std::allocator<void> > GeoVwSetSrvRequest;

typedef boost::shared_ptr< ::iri_sift::GeoVwSetSrvRequest> GeoVwSetSrvRequestPtr;
typedef boost::shared_ptr< ::iri_sift::GeoVwSetSrvRequest const> GeoVwSetSrvRequestConstPtr;


template <class ContainerAllocator>
struct GeoVwSetSrvResponse_ {
  typedef GeoVwSetSrvResponse_<ContainerAllocator> Type;

  GeoVwSetSrvResponse_()
  : geo_vw_set()
  {
  }

  GeoVwSetSrvResponse_(const ContainerAllocator& _alloc)
  : geo_vw_set(_alloc)
  {
  }

  typedef  ::iri_perception_msgs::GeoVwSet_<ContainerAllocator>  _geo_vw_set_type;
   ::iri_perception_msgs::GeoVwSet_<ContainerAllocator>  geo_vw_set;


  typedef boost::shared_ptr< ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GeoVwSetSrvResponse
typedef  ::iri_sift::GeoVwSetSrvResponse_<std::allocator<void> > GeoVwSetSrvResponse;

typedef boost::shared_ptr< ::iri_sift::GeoVwSetSrvResponse> GeoVwSetSrvResponsePtr;
typedef boost::shared_ptr< ::iri_sift::GeoVwSetSrvResponse const> GeoVwSetSrvResponseConstPtr;

struct GeoVwSetSrv
{

typedef GeoVwSetSrvRequest Request;
typedef GeoVwSetSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GeoVwSetSrv
} // namespace iri_sift

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b13d2865c5af2a64e6e30ab1b56e1dd5";
  }

  static const char* value(const  ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb13d2865c5af2a64ULL;
  static const uint64_t static_value2 = 0xe6e30ab1b56e1dd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "iri_sift/GeoVwSetSrvRequest";
  }

  static const char* value(const  ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sensor_msgs/Image image\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in src/image_encodings.cpp\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fbaeb4cf1b5d7cd6619b89880488beae";
  }

  static const char* value(const  ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfbaeb4cf1b5d7cd6ULL;
  static const uint64_t static_value2 = 0x619b89880488beaeULL;
};

template<class ContainerAllocator>
struct DataType< ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "iri_sift/GeoVwSetSrvResponse";
  }

  static const char* value(const  ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "iri_perception_msgs/GeoVwSet geo_vw_set\n\
\n\
\n\
================================================================================\n\
MSG: iri_perception_msgs/GeoVwSet\n\
iri_perception_msgs/GeoVw[] geo_vws\n\
\n\
================================================================================\n\
MSG: iri_perception_msgs/GeoVw\n\
uint32 x\n\
uint32 y\n\
uint32 word\n\
";
  }

  static const char* value(const  ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.image);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GeoVwSetSrvRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.geo_vw_set);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GeoVwSetSrvResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<iri_sift::GeoVwSetSrv> {
  static const char* value() 
  {
    return "daa8e81549d2bfdca961b9581eed855d";
  }

  static const char* value(const iri_sift::GeoVwSetSrv&) { return value(); } 
};

template<>
struct DataType<iri_sift::GeoVwSetSrv> {
  static const char* value() 
  {
    return "iri_sift/GeoVwSetSrv";
  }

  static const char* value(const iri_sift::GeoVwSetSrv&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "daa8e81549d2bfdca961b9581eed855d";
  }

  static const char* value(const iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "iri_sift/GeoVwSetSrv";
  }

  static const char* value(const iri_sift::GeoVwSetSrvRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "daa8e81549d2bfdca961b9581eed855d";
  }

  static const char* value(const iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "iri_sift/GeoVwSetSrv";
  }

  static const char* value(const iri_sift::GeoVwSetSrvResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // IRI_SIFT_SERVICE_GEOVWSETSRV_H

